mybatis:
  mapperLocations: classpath*:/mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true
#gateway:
#    names: api-gateway
config:
  jar: /Users/jcalaz/work/code/choerodon/api-gateway/target/app.jar
  file: application.yml
  type: register-server
  update-policy: add
service:
  name: api-gateway
  version: v23
  namespace: c7nf-staging
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/manager_service?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
register:
  host: http://127.0.0.1:9000/