mybatis:
  mapperLocations: classpath*:/mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true
gateway:
  names: api-gateway
config:
  file: application.yml
  type: db
  jar: /Users/jcalaz/work/code/choerodon/gateway-helper/target/app.jar
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/manager_service?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
service:
  name: gateway-helper