# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 1000
      min-spare: 30
  servlet:
    context-path: /
# mysql
spring:
  datasource:
    dynamic:
      primary: gen # 默认使用配置
      datasource:
        gen:
          driver-class-name: ${spring.datasource.driver-class-name:com.mysql.jdbc.Driver}
          url: ${spring.datasource.url:jdbc:mysql://localhost:3306?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT}
          username: ${spring.datasource.username:root}
          password: ${spring.datasource.password:root}
        platform: # 多数据源配置
          driver-class-name: com.mysql.jdbc.Driver
          url: "jdbc:mysql://localhost:3306?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT"
          username: "root"
          password: "root"
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  liquibase:
    enabled: false
# c7n 自定义配置
installer:
  jarPath: hhh/app.jar
#    init: true # 递归初始化jar包
#  skipFile: hzero-data-message-template-business.xlsx,fd_project.groovy # 指定跳过文件初始化

# hzero-installer 原生配置
hzero:
  upgrade:
    dataDir: choerodon/script/db/init-data
    groovyDir: choerodon/script/db/groovy
    fixDir: choerodon/script/db/fix-data
  data:
    mappingFile: ../hzero-resource/docs/mapping/service-mapping.xml # serviceMapping 文件位置

data:
  #  init: true # 是否初始化excel
  version: 0.25.0 # hzero必填参数 c7n用不上

# Mybatis配置
mybatis:
  mapperLocations: classpath*:mapper/**/*.xml

logging:
  level:
    root: info #日志级别 root表示所有包，也可以单独配置具体包 fatal error warn info debug trace off
